<div class="clear">
  <p><img class="float-left img-thumbnail mr-4 mt-2" src="/images/me/Curt-1964-Electric.png" width="98" alt="">Curt began playing guitar at age nine. Since 1978, he has been a serious student of jazz guitar. He had the great privilege and honor of studying with Chuck Anderson for more than 30 years. With Chuck’s guidance, Curt focused on jazz and contemporary guitar. With Chuck, no subject was off limits. Topics including arranging, private teaching, 20th century harmony, performing and working with other musicians, and many other innovative explorations.</p>

  <p><img class="float-right img-thumbnail ml-4 my-2 mb-3 img-thumbnail" src="/images/me/2015_ffukefest-mcW-sm.png" alt="">In the summer of 2003, Curt fell in love with the ukulele and all its possibilities. The ukulele has been the center of Curt’s energy ever since then. Curt’s journey exploring the ukulele began by accident on a CampFire USA trip to South Dakota planned by his wife, Bernadette. Curt searched the Internet for a small travel guitar to bring along, and rediscovered the ukulele instead. Curt began to pursue the potential of the ukulele upon their return from the trip.</p>

  <p>Researching the field of ukulele educational material, Curt realized that there was very little material on the ukulele appropriate for intermediate and advanced players. At that time, Curt had substantial understanding of music and guitar that he could apply to the ukulele. So, Curt methodically began to develop detailed lessons and write books for ukulele players, drawing on his knowledge and experience of playing jazz and contemporary guitar and studying with Chuck Anderson.</p>

    <p>Curt has developed an international reputation as a ukulele expert, having written more than 40 books and more than 800 lessons for the ukulele as well as several books for guitar and music.</p>

    <p>Visit Curt’s website at <a href="//learningukulele.com"><b>LearningUkulele.com</b> @svg('link')</a> to see his work as an author and educator. Curt conducts ukulele workshops and runs an annual ukulele festival entitled <a href="//funkyfretsukefest.com"><b>Funky Frets Ukulele Festival</b> @svg('link')</a> to great acclaim. He remains a professional musician. He recently released a jazz ukulele CD, <a href="{{ route('cds') }}"><b>&ldquo;How About More Uke?&rdquo;</b> @svg('link')</a>, exploring the ukulele with traditional and contemporary jazz repertoire and some of Curt’s original music, all of which showcase a nontraditional ukulele performance. Chuck Anderson was a valuable asset leading up to the recording of that CD with his help whipping the charts into shape and allowing us to record his great song Rain Shine. Curt also continue to perform live concerts. Curt, along with his wife Bernadette and daughter Kelly owns and operates the Funky Frets music store in Boyertown, PA, where he sells ukuleles and conducts music lessons. Curt also teaches via Skype.</p>

    <p class="text-center text-lg"> @svg('download', 'text-brand-lighter') Download <a href="/assets/txt/bio-Curt-Sheller-long.txt"><em>a plain text file</em></a> of this bio. @svg('file', 'text-brand-lighter')</p>
</div>
